import React, { Component } from 'react';
import BookList from '../ContainerComponents/BookList';
import BookDetail from '../ContainerComponents/BookDetail';

import './App.css';

/*
* Redux serves to construct the application state and
* React provides the views to display that state;
* The two libraries are inherently disconnected and it's only through the use of react-redux that we get clear connections between the two;
* Application state is generated by reducer functions;
*
* BookList is promoted to container;
* A container is a normal react component that gets bonded to the application state;
* In other words container is a component that has direct access to the state that's produced by Redux;
* Whenever the applications state changes the container will re-render as well;
* */

class App extends Component {
  render() {
    return (
      <div className="App container">
        <BookList />
        <BookDetail />
      </div>
    );
  }
}

export default App;
